version: '3.8'

services:
  web:
    container_name: restoran-backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/restoran_db
      - SECRET_KEY=Tubes TST
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: restoran-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restoran_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: